---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Repo Template for GitOps Deployments
  description: '<Description of the application>'
  tags:
    - kubernetes
    - homelab
    - infrastructure
  annotations:
    github.com/project-slug: cmoreira-dev/gitops.template
    backstage.io/kubernetes-id: homelab-bootstrap-k3s
    argocd/app-name: '<ApplicationSet Name>'
  links:
    - url: '<Placeholder for the application URL>'
      title: '<Placeholder for the application title>'
      icon: dashboard
spec:
  type: website
  lifecycle: lab
#  owner: platform-team
#  system: homelab
#  dependsOn:
#    - component:homelab-bootstrap-k3s
