generic-app:
  nameOverride: "teupadel-ui"

  namespace:
    create: true
    name: "teupadel"

  image:
    repository: "344965637185.dkr.ecr.us-east-1.amazonaws.com/teupadel/ui"
    tag: "latest"

  service:
    port: 80
    targetPort: 80 # porta real que o container escuta

  httpRoute:
    enabled: true
    gateway:
      name: nginx-gateway-teupadel-com
      namespace: nginx-gateway
    hostnames:
      - "www.teupadel.com"

    imagePullSecrets:
      - name: ecr-pull-secret

externalSecrets:
  enabled: true
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  secretName: "teupadel-ui-secret"
  data:
    - secretKey: some-key
      remoteRef:
        key: /homelab/teupadel/anthropic_ui_key
